### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nileshzala005** [twilio/twilio-client.js#284]
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
        
    With Angular 12, this is working fine in Angular 11
    
Angular CLI: 12.0.0
Node: 14.15.4
Package Manager: npm 6.14.10
OS: darwin x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1200.0 (cli-only)
@angular-devkit/core         12.0.0 (cli-only)
@angular-devkit/schematics   12.0.0 (cli-only)
@schematics/angular          12.0.0 (cli-only)

**Comment by msms007** [comment]
any updates or work around to this? still struggling to find a fix

**Comment by pgarzina** [comment]
experiencing the same issue, and is a blocker in updating to Angular 12.

**Comment by pgarzina** [comment]
@nileshzala005 @msms007 have you guys found a working workaround maybe? :)

**Comment by nileshzala005** [comment]
@pgarzina instead of NPM packages use CDN version or update to twilio 2.0 version

**Comment by pgarzina** [comment]
> @pgarzina instead of NPM packages use CDN version or update to twilio 2.0 version

thanks for the reply, we did migrate to 2.0 (@twilio/voice-sdk": "^2.0.1", - https://github.com/twilio/twilio-voice.js) but the error appears there as well (I tried it out on a blank angular 12.1.2 project).

I will try the CDN version as you suggested. thanks

**Comment by huannxdev** [comment]
Hi @pgarzina , Have you resolved your problem?. I got this when upgrading to angular 12

**Comment by pgarzina** [comment]
Hey @huannxdev 
we have not resolved the problem, we rolled back to angular 11 until Twilio fixes it - which will potentially take a few months.

there is a suggested workaround here https://github.com/twilio/twilio-voice.js/issues/28#issuecomment-909364340
which we didn't have time to try out yet, but hopefully it works.

**Comment by huannxdev** [comment]
Yeah, i revolved this by steps, you can try :
- npm i util
- add code into polyfill.ts file
`(window as any).process = {
  env: { DEBUG: undefined },
};`

**Comment by ashish-koshy** [comment]
I hope this helps someone facing this issue. I created a sample boilerplate ionic-angular project that can load .env files:
https://github.com/ashish-koshy/ionic-ng-pwa

Please do remember to create a .env file as it is not a part of this repo.

**Comment by Jeff-Stapleton** [comment]
> Yeah, i resolved this by steps, you can try :
> 
> * npm i util
> * add code into polyfill.ts file
>   `(window as any).process = { env: { DEBUG: undefined }, };`

If I am not mistaken this will simply define process with the object you are giving it -- it still won't read your environment variables

**Comment by ashish-koshy** [comment]
@Jeff-Stapleton 
Yes that's correect, this method alone would not work. The intent behind performing such a hack is for us to be able to avoid a browser/DOM exception when the browser tries to dereference an object called `process.env`. The problem here is that this object does not or should not exist within the context of a browser being used by a client.

`process.env` object only makes sense within the context of `NodeJS` which is a server side language having direct access to the operating system its running on as opposed to the JavaScript code running within a client's browser.  The `process.env` object allows NodeJS developers to load values specific to the environment they deploy their server side code to. 

Now, how or why the `process.env` object is being dereferenced in this manner by twilio's `client side` library is unknown to me. This is a question that has to be answered or fixed by the twilio developers.

You need to perform a few additional steps to actually make this work. You have to manually provide the `process.env` object to the browser before it tries to execute any of your javascript code. Again, keep in mind that this is a dirty hack that twilio developers shouldn't be expecting us to perform : 

1. Install the `dotenv` package as a dev dependency `npm install --save-dev dotenv`
2. Create  a file called `.env`  at the root of your project and add some dummy key value pairs seperated by the `=` symbol (the non existent ones that twilio's code is trying to blindly access):

![image](https://user-images.githubusercontent.com/55425558/179648549-47d6c38d-07dd-4e3a-9efb-0b483384a3f0.png)

3. Add the `.env` file to your `.gitignore` (you don't want to commit this file) :

![image](https://user-images.githubusercontent.com/55425558/179647863-3c505421-9f93-4321-a830-d7a3895cbdc4.png)

4. Now add another file at the root of your project called `webpack.config.js` :

![image](https://user-images.githubusercontent.com/55425558/179648070-65ee0a3f-cceb-4ec2-a0a6-71acd9931e3b.png)

You can find the code here:
https://github.com/ashish-koshy/ionic-ng-pwa/blob/main/webpack.config.js

In this step you are asking the webpack module bundler to bundle a pseudo object called `process.env` at build time so that the browser would eventually be able to read it at run time withiut throwing exceptions. The key value pairs for the `process.env` object would get picked from within the `.env` file you just created above

5. Then, in your `angular.json` file add the setting that allows you to load custom webpack configuration at build time:

![image](https://user-images.githubusercontent.com/55425558/179649390-35fd4763-6c4a-400d-9b4c-66919e01ed1a.png)

You can find the code here:
https://github.com/ashish-koshy/ionic-ng-pwa/blob/main/angular.json


And finally for the love of god, please do not use this hack in your production code. Keep the `.env` file listed within your `.gitignore`

**Comment by Hitsaa** [comment]
I resolved the issue by adding 

(window as any).process = {
    env: { DEBUG: undefined },
  };

in polyfill.ts file.

**Comment by elenitaex5** [comment]
I've found the real solution. This problem is in `util` library (`browserify/node-util`) having **webpack 5**
Real solution is here https://github.com/browserify/node-util/issues/57#issuecomment-764436352

And no file has to be changed except `webpack.config.js` once

**Comment by davidecarpini** [comment]
if you need to deploy Angular 6 with serve:

**polyfills.ts**
```
(window as any).global = window;
global.Buffer = global.Buffer || require('buffer').Buffer;
(window as any).process = {
    env: { DEBUG: undefined },
    version: [], // to avoid undefined.slice error
};
```

**Comment by 13601101** [comment]
Actually im  getting  below error after adding above code in polyfills.ts


An error was thrown in afterAll
  Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
  TypeError: Cannot read properties of undefined (reading 'prototype')
      at Object.18606 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/express/lib/response.js:43:45)
      at require (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.72540 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/express/lib/express.js:22:11)
      at module (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.44202 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/express/index.js:11:1)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Module.56938 (http://localhost:9876/_karma_webpack_/main.js:189477:65)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at __webpack_exec__ (http://localhost:9876/_karma_webpack_/main.js:869311:48)
      at http://localhost:9876/_karma_webpack_/main.js:869312:2772
Chrome 124.0.0.0 (Windows 10): Executed 51 of 462 (1 FAILED) ERROR (0.683 secs / 0.593 secs)
Chrome 124.0.0.0 (Windows 10) ERROR
  An error was thrown in afterAll
  Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
  TypeError: Cannot read properties of undefined (reading 'prototype')
      at Object.18606 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/express/lib/response.js:43:45)
      at require (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.72540 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/express/lib/express.js:22:11)
      at module (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.44202 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/express/index.js:11:1)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Module.56938 (http://localhost:9876/_karma_webpack_/main.js:189477:65)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at __webpack_exec__ (http://localhost:9876/_karma_webpack_/main.js:869311:48)
      at http://localhost:9876/_karma_webpack_/main.js:869312:2772

**Comment by karrivinodh** [comment]
src_app_app_component_ts.js:1 ERROR ReferenceError: process is not defined
    at 22122 (util.js:109:1)
    at __webpack_require__ (bootstrap:19:1)
    at sharing:171:1
    at __webpack_require__.m.<computed> (consumes:1602:1)
    at __webpack_require__ (bootstrap:19:1)
    at 68232 (progress-bar.component.ts:20:28)
    at __webpack_require__ (bootstrap:19:1)
    at 20092 (app-routing.module.ts:26:25)
    at __webpack_require__ (bootstrap:19:1)
    at 94114 (taskmapping.component.ts:35:162)

iam getting this error when child application is running in parent application using module federation any idea
